<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a0a746573742e70726f746f12047465737422160a074d6573736167" .
            "65120b0a036d7367180120012809322e0a0450696e6712260a0450696e67" .
            "120d2e746573742e4d6573736167651a0d2e746573742e4d657373616765" .
            "2200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

