<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a0a746573742e70726f746f12077365727669636522160a074d65" .
            "7373616765120b0a036d736718012001280932be010a0454657374122c0a" .
            "044563686f12102e736572766963652e4d6573736167651a102e73657276" .
            "6963652e4d6573736167652200122d0a055468726f7712102e7365727669" .
            "63652e4d6573736167651a102e736572766963652e4d6573736167652200" .
            "122b0a0344696512102e736572766963652e4d6573736167651a102e7365" .
            "72766963652e4d6573736167652200122c0a04496e666f12102e73657276" .
            "6963652e4d6573736167651a102e736572766963652e4d65737361676522" .
            "00620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

