<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a0a746573742e70726f746f12077365727669636522160a074d65" .
            "7373616765120b0a036d7367180120012809220e0a0c456d7074794d6573" .
            "7361676532f6010a0454657374122c0a044563686f12102e736572766963" .
            "652e4d6573736167651a102e736572766963652e4d657373616765220012" .
            "2d0a055468726f7712102e736572766963652e4d6573736167651a102e73" .
            "6572766963652e4d6573736167652200122b0a0344696512102e73657276" .
            "6963652e4d6573736167651a102e736572766963652e4d65737361676522" .
            "00122c0a04496e666f12102e736572766963652e4d6573736167651a102e" .
            "736572766963652e4d657373616765220012360a0450696e6712152e7365" .
            "72766963652e456d7074794d6573736167651a152e736572766963652e45" .
            "6d7074794d6573736167652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

