<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

namespace Health;

if (false) {
    /**
     * This class is deprecated. Use Health\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Health\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Health\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

