<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a0a746573742e70726f746f12077365727669636522160a074d65" .
            "7373616765120b0a036d736718012001280922160a05436c617373120d0a" .
            "0576616c7565180120012803323b0a0b50696e6753657276696365122c0a" .
            "0450696e6712102e736572766963652e4d6573736167651a102e73657276" .
            "6963652e4d6573736167652200323b0a0b506f6e6753657276696365122c" .
            "0a04506f6e6712102e736572766963652e4d6573736167651a102e736572" .
            "766963652e4d6573736167652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

